### ISSUE TITLE
Could you please provide standalone executable?

### ISSUE THREAD

**Issue by m7mdyahia** [arturasn/mdb2sqlite#2]
Could you please provide standalone executable?

**Comment by lymereJ** [comment]
@m7mdyahia it looks like there is a standalone executable in the bin folder.

**Comment by m7mdyahia** [comment]
yes @lymereJ  but it didn't work for me on windows 10 64 bit
so I re-build the project and re-build wx-widgets

**Comment by m7mdyahia** [comment]
#3 added the 64bit excutable

**Comment by imacmill** [comment]
I just tried both the 32-bit and 64-bit executables on both Windows 10 and Windows 7 (both 64-bit), and the programs crash when clicking either the Dump or Convert buttons ("An unhandled exception occured. Press Abort to terminate"). 

Any ideas?

**Comment by m7mdyahia** [comment]
download the sources and recompile
it isn't an easy job

**Comment by arturasn** [comment]
imacmill, sorry I was not around is it still crashing?
