### ISSUE TITLE
relationship one to one is missing

### ISSUE THREAD

**Issue by erdeveloper** [arturasn/mdb2sqlite#5]
If I create relationship one to one for primary key in ms access then it is not converted to sqlite db.
I have two tables t_device and t_device_data_last.
There are primary keys:
t_device.id
t_device_data_last.deviceId
and it has relationship one-to-one.

detail from ms access:
Relationships
         t_devicet_device_data_last
                            t_device                       t_device_data_last
                    id                         1     1  deviceId

                  Attributes:                Unique; Enforced; Cascade Updates; Cascade Deletes
                  RelationshipType:          One-To-One

detail from sqllite (dump.txt)

CREATE TABLE `t_device_data_last` (`deviceId` REAL NOT NULL PRIMARY KEY UNIQUE,`dateTime` TEXT COLLATE NOCASE,`temperature` REAL,`humidity` REAL DEFAULT 0,`batteryPower` REAL DEFAULT 0,`dateTimeInt` REAL,`runCnt` INTEGER,`restarfromZeroCnt` INTEGER,`lastRunCnt` INTEGER,`runningTime` INTEGER,`pressure` REAL DEFAULT 0,`co2` INTEGER DEFAULT 0,`tvoc` INTEGER DEFAULT 0,`baseLineReg` INTEGER DEFAULT 0,`current` INTEGER DEFAULT 0 /*current in micro ampere */,`voltage` INTEGER DEFAULT 0 /*voltage */);

there is missing FOREIGN KEY(deviceId) REFERENCES t_device(id) in dump.txt for CREATE TABLE of t_device_data_last table.

The table t_device_data_last is created before t_device.
How is check which table should be created first? Is it important during conversion?

**Comment by arturasn** [comment]
Could you provide the database you are trying to convert?
Yes it is important referenced table should already be created.

**Comment by arturasn** [comment]
And afcourse Foreign key are only supported if you check the checkbox in the settings dialog

**Comment by arturasn** [comment]
By the way you probably have the last setting checked: "Foreign key Both primary fields"
If this setting is checked and there is a relationship primary key - primary key. It is not created, so you should uncheck it since it is checked by default.

**Comment by erdeveloper** [comment]
Yes, I have the last setting checked: "Foreign key Both primary fields". But if I unchecked it there is assert in method
int CRelationships::Findind ( CString *&sTableNames , CString &sSearchedTable , const unsigned &nTreeSize )
   {
   for ( unsigned i3 = 0; i3 < nTreeSize; ++i3 )
      {
      if ( !( sTableNames [ i3 ].Compare ( sSearchedTable ) ) )
         return i3;
      }

   ASSERT ( FALSE );
   return -1;
   }

**Comment by erdeveloper** [comment]
Test.mdb
[Test.zip](https://github.com/arturasn/mdb2sqlite/files/1494933/Test.zip)

**Comment by arturasn** [comment]
Fixed, MS was adding additional system tables which were not checked during relationship creation.
