### ISSUE TITLE
Default value for DATETIME columns may be specified as "Now()" in mdb database, but sqlite does not support "Now()"

### ISSUE THREAD

**Issue by oliort** [arturasn/mdb2sqlite#6]
Default value for DATETIME columns may be specified as "Now()" in mdb database, but sqlite does not support "Now()". Converter should replace "Now()" to "CURRENT_TIMESTAMP".

**Comment by oliort** [comment]
Converter should replace "Now()" to "CURRENT_TIMESTAMP".

**Comment by arturasn** [comment]
Thank you for the issue.
Updated the default value with your corresponding fix.
