### ISSUE TITLE
Linux release?

### ISSUE THREAD

**Issue by platipusica** [arturasn/mdb2sqlite#7]
Hi there, 

thanks for your contrib, it is really needed. I just used Easysoft odbc trail driver to do conversion. Prior that used Jackcess.

Is there any possibility for Linux distro release or some "how to"? Also, since only using Linux, and can't try Win version atm, is there a command line option?

Cheers

**Comment by slidertom** [comment]
just install virtual box or vmware or kvm and run windows on Linux distro.

**Comment by platipusica** [comment]
Thanks!

Win7? No thanks :) ok, so jackcess can convert 30-40mb DB in about 4-5mins. Plain tables.
This tool can only dump the DB, the conversion never finishes, CPU is on 100% after 5mins, so no go. On Win10 tho.

Just as food for thought, the Easysoft with Python simple script does conversion of the same file in 5secs. Yes, 5!
But the buggers asking for £899 for it, so no go.

Good luck.
